### ISSUE TITLE
npm build errror

### ISSUE THREAD

**Issue by MagnusIIIBR** [reecebedding/EveCM#3]
> evecm@ build C:\Users\Admin\Downloads\EveCM-master\EveCM
> webpack --mode development

clean-webpack-plugin: C:\Users\Admin\Downloads\EveCM-master\EveCM\wwwroot\* has been removed.
i ｢atl｣: Using typescript@2.8.1 from typescript
i ｢atl｣: Using tsconfig.json from C:\Users\Admin\Downloads\EveCM-master\EveCM/tsconfig.json
i ｢atl｣: Checking started in a separate process...
i ｢atl｣: Time: 241ms

 SMP  ⏱
General output time took 18.97 secs

 SMP  ⏱  Plugins
MiniCssExtractPlugin took 0.079 secs
Object took 0.014 secs
ProvidePlugin took 0 secs

 SMP  ⏱  Loaders
C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\babel-loader\lib\index.js, and
C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\awesome-typescript-loader\dist\entry.js, and
C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tslint-loader\index.js took 12.19 secs
  module count = 28
modules with no loaders took 3.87 secs
  module count = 460
C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\mini-css-extract-plugin\dist\loader.js, and
C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\css-loader\index.js, and
C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\sass-loader\lib\loader.js took 2.19 secs
  module count = 2
C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\css-loader\index.js, and
C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\sass-loader\lib\loader.js took 2.12 secs
  module count = 2
C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\css-loader\index.js took 0.458 secs
  module count = 2
C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\url-loader\dist\cjs.js took 0.178 secs
  module count = 5
C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\style-loader\index.js, and
C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\css-loader\index.js took 0.019 secs
  module count = 2

Hash: 61ba8899cbddf25c9f4e
Version: webpack 4.5.0
Time: 18981ms
Built at: 2018-10-27 12:50:27
                                   Asset      Size  Chunks             Chunk Names
images/eve-sso-associate-black-small.png  2.69 KiB          [emitted]
                             js/admin.js  3.43 MiB   admin  [emitted]  admin
                              js/home.js  2.99 MiB    home  [emitted]  home
                            js/vendor.js  2.61 MiB  vendor  [emitted]  vendor
                             favicon.ico  31.3 KiB          [emitted]
                    images/container.png  1.06 KiB          [emitted]
                            js/global.js  13.6 KiB  global  [emitted]  global
    images/eve-sso-login-black-large.png  2.25 KiB          [emitted]
    images/eve-sso-login-white-large.png   2.2 KiB          [emitted]
    images/eve-sso-login-black-small.png  1.58 KiB          [emitted]
                        images/guest.png  6.31 KiB          [emitted]
    images/eve-sso-login-white-small.png  1.51 KiB          [emitted]
                     images/settings.png  2.56 KiB          [emitted]
[./ClientApp/app/actions/actionTypeKeys.ts] 921 bytes {admin} {home} [built]
[./ClientApp/app/actions/bulletinActions.ts] 2.59 KiB {home} [built]
[./ClientApp/app/actions/connectors/bulletinConnector.ts] 825 bytes {home} [built]
[./ClientApp/app/actions/connectors/userConnector.ts] 377 bytes {admin} {home} [built]
[./ClientApp/app/actions/userActions.ts] 989 bytes {admin} {home} [built]
[./ClientApp/app/global.ts] 39 bytes {global} [built]
[./ClientApp/app/lib/user-utils.ts] 249 bytes {home} [built]
[./ClientApp/app/reducers/initialState.ts] 635 bytes {admin} {home} [built]
[./ClientApp/app/reducers/rootReducer.ts] 799 bytes {admin} {home} [built]
[./ClientApp/app/store/configureStore.ts] 965 bytes {admin} {home} [built]
[./ClientApp/app/style.scss] 6.89 KiB {global} [built] [failed] [1 error]
[./ClientApp/front.js] 1.49 KiB {vendor} [built]
[./ClientApp/vendor.js] 366 bytes {vendor} [built]
[./ClientApp/vendor.scss] 6.89 KiB {vendor} [built] [failed] [1 error]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {admin} {home} {vendor} [built]
    + 484 hidden modules

ERROR in ./ClientApp/vendor.scss
Module build failed: ModuleBuildError: Module build failed: Error: Missing binding C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\node-sass\vendor\win32-x64-59\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 9.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:225:3)
    at NormalModule.build (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:343:15)
    at Compilation.buildModule (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\Compilation.js:361:10)
    at moduleFactory.create (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\Compilation.js:717:12)
    at factory (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook [as _callAsync] (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tapable\lib\Hook.js:35:21)
    at resolver (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:126:29)
    at process.nextTick (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:304:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)
    at runLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:242:20)
    at C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:225:3)
    at NormalModule.build (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:343:15)
    at Compilation.buildModule (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\Compilation.js:361:10)
    at moduleFactory.create (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\Compilation.js:717:12)
    at factory (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook [as _callAsync] (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tapable\lib\Hook.js:35:21)
    at resolver (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:126:29)
    at process.nextTick (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:304:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)
 @ ./ClientApp/vendor.js 14:0-23

ERROR in ./ClientApp/app/style.scss
Module build failed: ModuleBuildError: Module build failed: Error: Missing binding C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\node-sass\vendor\win32-x64-59\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 9.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at loadLoader (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:225:3)
    at NormalModule.build (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:343:15)
    at Compilation.buildModule (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\Compilation.js:361:10)
    at moduleFactory.create (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\Compilation.js:717:12)
    at factory (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook [as _callAsync] (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tapable\lib\Hook.js:35:21)
    at resolver (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:126:29)
    at process.nextTick (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:304:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)
    at runLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:242:20)
    at C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:225:3)
    at NormalModule.build (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:343:15)
    at Compilation.buildModule (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\Compilation.js:361:10)
    at moduleFactory.create (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\Compilation.js:717:12)
    at factory (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
    at hooks.afterResolve.callAsync (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook [as _callAsync] (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tapable\lib\Hook.js:35:21)
    at resolver (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:126:29)
    at process.nextTick (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:304:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)
 @ ./ClientApp/app/global.ts 3:0-23
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/sass-loader/lib/loader.js??ref--5-2!ClientApp/app/style.scss:
    [./node_modules/css-loader/index.js??ref--5-1!./node_modules/sass-loader/lib/loader.js??ref--5-2!./ClientApp/app/style.scss] ./node_modules/css-loader??ref--5-1!./node_modules/sass-loader/lib/loader.js??ref--5-2!./ClientApp/app/style.scss 4.17 KiB {mini-css-extract-plugin} [built] [failed] [1 error]

    ERROR in ./ClientApp/app/style.scss (./node_modules/css-loader??ref--5-1!./node_modules/sass-loader/lib/loader.js??ref--5-2!./ClientApp/app/style.scss)
    Module build failed: Error: Missing binding C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\node-sass\vendor\win32-x64-59\binding.node
    Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 9.x

    Found bindings for the following environments:
      - Windows 64-bit with Node.js 10.x

    This usually happens because your environment has changed since running `npm install`.
    Run `npm rebuild node-sass --force` to build the binding for your current environment.
        at module.exports (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\node-sass\lib\binding.js:15:13)
        at Object.<anonymous> (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\node-sass\lib\index.js:14:35)
        at Module._compile (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
        at Object.Module._extensions..js (module.js:671:10)
        at Module.load (module.js:573:32)
        at tryModuleLoad (module.js:513:12)
        at Function.Module._load (module.js:505:3)
        at Module.require (module.js:604:17)
        at require (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
        at Object.<anonymous> (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\sass-loader\lib\loader.js:3:14)
        at Module._compile (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
        at Object.Module._extensions..js (module.js:671:10)
        at Module.load (module.js:573:32)
        at tryModuleLoad (module.js:513:12)
        at Function.Module._load (module.js:505:3)
        at Module.require (module.js:604:17)
        at require (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
        at loadLoader (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
        at C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:173:18
        at loadLoader (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\loadLoader.js:36:3)
        at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at runLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
        at NormalModule.doBuild (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:225:3)
        at NormalModule.build (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:343:15)
        at Compilation.buildModule (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\Compilation.js:361:10)
        at moduleFactory.create (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\Compilation.js:717:12)
        at factory (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
        at hooks.afterResolve.callAsync (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
        at AsyncSeriesWaterfallHook.lazyCompileHook [as _callAsync] (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tapable\lib\Hook.js:35:21)
        at resolver (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:126:29)
        at process.nextTick (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:304:9)
        at process._tickCallback (internal/process/next_tick.js:150:11)
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--5-1!node_modules/sass-loader/lib/loader.js??ref--5-2!ClientApp/vendor.scss:
    [./node_modules/css-loader/index.js??ref--5-1!./node_modules/sass-loader/lib/loader.js??ref--5-2!./ClientApp/vendor.scss] ./node_modules/css-loader??ref--5-1!./node_modules/sass-loader/lib/loader.js??ref--5-2!./ClientApp/vendor.scss 4.17 KiB {mini-css-extract-plugin} [built] [failed] [1 error]

    ERROR in ./ClientApp/vendor.scss (./node_modules/css-loader??ref--5-1!./node_modules/sass-loader/lib/loader.js??ref--5-2!./ClientApp/vendor.scss)
    Module build failed: Error: Missing binding C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\node-sass\vendor\win32-x64-59\binding.node
    Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 9.x

    Found bindings for the following environments:
      - Windows 64-bit with Node.js 10.x

    This usually happens because your environment has changed since running `npm install`.
    Run `npm rebuild node-sass --force` to build the binding for your current environment.
        at module.exports (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\node-sass\lib\binding.js:15:13)
        at Object.<anonymous> (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\node-sass\lib\index.js:14:35)
        at Module._compile (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
        at Object.Module._extensions..js (module.js:671:10)
        at Module.load (module.js:573:32)
        at tryModuleLoad (module.js:513:12)
        at Function.Module._load (module.js:505:3)
        at Module.require (module.js:604:17)
        at require (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
        at Object.<anonymous> (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\sass-loader\lib\loader.js:3:14)
        at Module._compile (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
        at Object.Module._extensions..js (module.js:671:10)
        at Module.load (module.js:573:32)
        at tryModuleLoad (module.js:513:12)
        at Function.Module._load (module.js:505:3)
        at Module.require (module.js:604:17)
        at require (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
        at loadLoader (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
        at C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:173:18
        at loadLoader (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\loadLoader.js:36:3)
        at iteratePitchingLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at runLoaders (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
        at NormalModule.doBuild (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:225:3)
        at NormalModule.build (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModule.js:343:15)
        at Compilation.buildModule (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\Compilation.js:361:10)
        at moduleFactory.create (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\Compilation.js:717:12)
        at factory (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
        at hooks.afterResolve.callAsync (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
        at AsyncSeriesWaterfallHook.lazyCompileHook [as _callAsync] (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\tapable\lib\Hook.js:35:21)
        at resolver (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:126:29)
        at process.nextTick (C:\Users\Admin\Downloads\EveCM-master\EveCM\node_modules\webpack\lib\NormalModuleFactory.js:304:9)
        at process._tickCallback (internal/process/next_tick.js:150:11)
Could not find a matching event to end plugins Object/Compiler/afterEmit { id: 508 }
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! evecm@ build: `webpack --mode development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the evecm@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2018-10-27T14_50_27_711Z-debug.log
PS C:\Users\Admin\Downloads\EveCM-master\EveCM>

**Comment by MagnusIIIBR** [comment]
Due my version, need run this command: npm rebuild node-sass --force
